/**
 * Generates `src/engine/landData.ts` from the Natural Earth 110m land polygons.
 *
 * Run it with `bun run --cwd apps/showcase land`; the generated module is committed, so the app
 * never fetches the coastlines at runtime.
 */

const SOURCE =
  'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson'

const OUTPUT = `${import.meta.dir}/../src/engine/landData.ts`

/** A GeoJSON position, `[longitude, latitude]` in degrees. */
type Position = [number, number]

interface Feature {
  geometry: {
    type: string
    coordinates: Position[][] | Position[][][]
  }
}

function toXyz(lng: number, lat: number): [number, number, number] {
  const phi = (lat * Math.PI) / 180
  const lambda = (lng * Math.PI) / 180
  const cosPhi = Math.cos(phi)
  return [cosPhi * Math.cos(lambda), cosPhi * Math.sin(lambda), Math.sin(phi)]
}

/** Collects the outer ring of every polygon, which is what a coastline hairline needs. */
function outerRings(features: Feature[]): Position[][] {
  const rings: Position[][] = []
  for (const feature of features) {
    const { type, coordinates } = feature.geometry
    if (type === 'Polygon') {
      rings.push((coordinates as Position[][])[0])
    } else if (type === 'MultiPolygon') {
      for (const polygon of coordinates as Position[][][]) rings.push(polygon[0])
    }
  }
  return rings
}

/** Packs the rings as `ringCount`, `vertexCount`, the offsets and the unit-sphere XYZ. */
function pack(rings: Position[][]): Uint8Array {
  const vertexCount = rings.reduce((total, ring) => total + ring.length, 0)
  const header = 2 + rings.length + 1
  const bytes = new ArrayBuffer(header * 4 + vertexCount * 3 * 4)
  const counts = new Uint32Array(bytes, 0, header)
  const xyz = new Float32Array(bytes, header * 4, vertexCount * 3)

  counts[0] = rings.length
  counts[1] = vertexCount
  let vertex = 0
  rings.forEach((ring, index) => {
    counts[2 + index] = vertex
    for (const [lng, lat] of ring) {
      const point = toXyz(lng, lat)
      xyz[vertex * 3] = point[0]
      xyz[vertex * 3 + 1] = point[1]
      xyz[vertex * 3 + 2] = point[2]
      vertex += 1
    }
  })
  counts[2 + rings.length] = vertex

  return new Uint8Array(bytes)
}

const response = await fetch(SOURCE)
if (!response.ok) throw new Error(`natural earth answered ${response.status}`)
const rings = outerRings(((await response.json()) as { features: Feature[] }).features)
const payload = pack(rings)
const vertexCount = rings.reduce((total, ring) => total + ring.length, 0)

const module = `// Generated by \`bun run land\` from Natural Earth 110m land (public domain). Do not edit.

/** Holds \`uint32\` ring count, vertex count and offsets, then the unit-sphere \`float32\` XYZ. */
export const LAND_BASE64 =
  '${Buffer.from(payload).toString('base64')}'
`

await Bun.write(OUTPUT, module)
console.log(`${rings.length} rings, ${vertexCount} vertices, ${payload.length} bytes`)
